Dockerfile updated and stable git server
- The Dockerfile has been updated to run a git local server
and new packages were added to the file
- The stddock file has been added to simulate a standard host
with Docker
- The newgu and new-repo files were updated to run with the new
git local server and using the git-shell shell

diff --git a/bin/new-repo b/bin/new-repo
--- a/bin/new-repo
+++ b/bin/new-repo
@@ -2,6 +2,11 @@
 
 if [[ $USER == git ]];
 then
+    if [[ $(dirname /home/git/$1) == /home/git ]]; then
+        echo "Unable to write repo in path /home/git/$1" | tee -a git-audit.log
+        exit 1
+    fi
+
     if [[ "$1" =~ \.git$ ]]; then
         repo=$1
     else
@@ -10,30 +15,31 @@ then
 
     mkdir "$repo" &>/dev/null
     if [ $? -ne 0 ]; then
-        echo "Error creating directoy \"$repo\""
-        exit 1
+        echo "Error creating directoy \"$repo\"" | tee -a git-audit.log
+        exit 2
     fi
 
     chmod 700 -R "$repo" &>/dev/null
     if [ $? -ne 0 ]; then
-        echo "Error with permissions 700 to directoy \"$repo\""
-        exit 2
+        echo "Error with permissions 700 to directoy \"$repo\"" | tee -a git-audit.log
+        exit 3
     fi
 
     ln -rs "$repo" "$(echo $repo | sed "s/\.git$//g")" &>/dev/null
     if [ $? -ne 0 ]; then
-        echo "Error linking directoy \"$repo\""
-        exit 3
+        echo "Error linking directoy \"$repo\"" | tee -a git-audit.log
+        exit 4
     fi
 
     cd "$repo"
     if [ $? -ne 0 ]; then
-        echo "Error changing to directoy \"$repo\""
-        exit 4
+        echo "Error changing to directoy \"$repo\"" | tee -a git-audit.log
+        exit 5
     fi
 
     git init --bare
     echo "ref: refs/heads/main" > HEAD
+
 else
     if [ $# -lt 2 -o $# -gt 2 ]; then
         echo "More or less arguments used"
diff --git a/bin/newgu b/bin/newgu
--- a/bin/newgu
+++ b/bin/newgu
@@ -1,20 +1,71 @@
 #!/bin/bash
 
-if [[ $USER == git ]];
-then
-    mkdir "$1"
-    if [ $? -ne 0 ]; then
-        echo "Error creating user \"$1\""
+if [[ $USER == git ]]; then
+    user=$1
+    ssh_key=$2
+
+    [[ ! -d /home/git/.ssh ]] && mkdir -p /home/git/.ssh
+    [[ ! -f /home/git/.ssh/authorized_keys ]] && touch /home/git/.ssh/authorized_keys
+
+    if [[ -d $user/ ]]; then
+        echo "User \"$user\" already exists" | tee -a git-audit.log
         exit 1
     fi
 
-    if [[ $2 != "" ]]; then
-        echo "$2" | tee -a .ssh/authorized_keys
-        if [ $? -ne 0 ]; then
-            echo "Error adding ssh keys to authorized_keys"
-            exit 2
-        fi
+    mkdir "$user"
+    if [ $? -ne 0 ]; then
+        echo "Error creating user \"$user\"" | tee -a git-audit.log
+        exit 2
     fi
+    echo "User \"$user\" created" >> git-audit.log
+
+    echo "command=\"$user\" $ssh_key" | tee -a .ssh/authorized_keys
+    if [ $? -ne 0 ]; then
+        echo "Error adding ssh keys to authorized_keys" | tee -a git-audit.log
+        exit 3
+    fi
+    echo "ssh key for user \"$user\" added successfully" >> git-audit.log
+
+    [[ ! -f /home/git/git-shell-commands/$user ]] && touch /home/git/git-shell-commands/$user
+    echo -e "#!/bin/bash
+
+if [[ \"\$SSH_ORIGINAL_COMMAND\" =~ ^git-upload ]]; then
+    cmd=\$(echo \$SSH_ORIGINAL_COMMAND | cut -d' ' -f1)
+    repo=\$(echo \$SSH_ORIGINAL_COMMAND | cut -d' ' -f2 | sed \"s/'//g\")
+
+    if [[ ! \"\$repo\" =~ ^$user ]]; then
+        exit 1
+    fi
+
+    \$cmd \$repo
+
+elif [[ \"\$SSH_ORIGINAL_COMMAND\" =~ ^git-receive ]]; then
+    cmd=\$(echo \$SSH_ORIGINAL_COMMAND | cut -d' ' -f1)
+    repo=\$(echo \$SSH_ORIGINAL_COMMAND | cut -d' ' -f2 | sed \"s/'//g\")
+
+    if [[ ! \"\$repo\" =~ ^$user ]]; then
+        exit 1
+    fi
+
+    \$cmd \$repo
+
+elif [[ \"\$SSH_ORIGINAL_COMMAND\" =~ ^new-repo ]]; then
+    echo \"\$(date +\"%Y/%m/%d %H:%M:%S\") - $user - running git-shell command: \\\"\$SSH_ORIGINAL_COMMAND\\\"\" >> git-audit.log
+
+    repo=\$(echo \$SSH_ORIGINAL_COMMAND | cut -d' ' -f2)
+    if [[ ! \"\$repo\" =~ ^$user ]]; then
+        exit 1
+    fi
+
+    ./git-shell-commands/new-repo \$repo
+
+else
+    echo \"$user: E002: Unrecognized command: \\\"\$SSH_ORIGINAL_COMMAND\\\"\" >> git-audit.log
+    exit 2
+fi\n" > /home/git/git-shell-commands/$user
+    chmod 740 /home/git/git-shell-commands/$user
+    echo "bin file for user \"$user\" created successfully" >> git-audit.log
+
 else
     echo "$2" | grep -P '(\s|[^\w])' >/dev/null
     if [ $? -eq 0 ]; then
@@ -22,13 +73,11 @@ else
         exit 1
     fi
 
-    if [ $# -eq 2 ]; then
-        ssh git@$1 "newgu $2"
-    elif [ $# -eq 3 ]; then
+    if [ $# -eq 3 ]; then
         ssh git@$1 "newgu $2 \"$3\""
     else
         echo "More or less arguments used"
-        echo "Use: $0 <host> <username> <optional ssh_key>"
+        echo "Use: $0 <host> <username> <ssh_key>"
     fi
 fi
 
