Git and vim updated
- newRepo file updated
- newGitUser file updated
- .vimrc file updated

diff --git a/bin/newGitUser b/bin/newGitUser
--- a/bin/newGitUser
+++ b/bin/newGitUser
@@ -7,7 +7,28 @@ then
         echo "Error creating user \"$1\""
         exit 1
     fi
+
+    if [[ $2 != "" ]]; then
+        echo "$2" | tee -a .ssh/authorized_keys
+        if [ $? -ne 0 ]; then
+            echo "Error adding ssh keys to authorized_keys"
+            exit 2
+        fi
+    fi
 else
-    ssh git@$1 "./newGitUser $2"
+    echo "$2" | grep -P '(\s|[^\w])' >/dev/null
+    if [ $? -eq 0 ]; then
+        echo "Invalid username"
+        exit 1
+    fi
+
+    if [ $# -eq 2 ]; then
+        ssh git@$1 "newGitUser $2"
+    elif [ $# -eq 3 ]; then
+        ssh git@$1 "newGitUser $2 \"$3\""
+    else
+        echo "More or less arguments used"
+        echo "Use: $0 <host> <username> <optional ssh_key>"
+    fi
 fi
 
diff --git a/bin/newRepo b/bin/newRepo
--- a/bin/newRepo
+++ b/bin/newRepo
@@ -2,7 +2,7 @@
 
 if [[ $USER == git ]];
 then
-    repo=$(echo "$repo" | sed "s/\.git//")
+    repo=$(echo "$1" | sed "s/\.git//")
 
     mkdir "$repo"
     if [ $? -ne 0 ]; then
@@ -31,6 +31,17 @@ then
     git init --bare
     echo "ref: refs/heads/main" > HEAD
 else
-    ssh git@$1 "./newRepo $2"
+    if [ $# -lt 2 -o $# -gt 2 ]; then
+        echo "More or less arguments used"
+        echo "Use: $0 <host> <reponame>"
+    fi
+
+    echo "$2" | grep -P "[ !@#$%^&*()\[\]\{\}\"'<>,.?\\|]" >/dev/null
+    if [ $? -eq 0 ]; then
+        echo "Invalid repo name"
+        exit 1
+    fi
+
+    ssh git@$1 "newRepo $2"
 fi
 
